export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const FIND_REVIEWS_REQUEST = 'FIND_REVIEWS_REQUEST';
export const FIND_REVIEWS_SUCCESS = 'FIND_REVIEWS_SUCCESS';
export const FIND_REVIEWS_FAILURE = 'FIND_REVIEWS_FAILURE';
